# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c925e80a1b17e2cb7a7ef0d780d1462d3743cbfd9a2658ce3a8a2264a213e06f0322fcef7a09adeb9eda0ddba037bfacdcc562cc3ff51487b17a65c27b9639eb

test:
  secret_key_base: 9755687bd40b18d8abbcbdb2a64b08be74bb43c32f6fff0c35f9638e2fb3525799e991bead7cf9bdd6ff32425129305259f82ca1b8d5364fc7d6c7e0e416356a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
